FROM node:lts-bookworm AS dev
WORKDIR /var/api
COPY --chown=node:node backend/ ./

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install \
    git \
    iputils-ping \
    procps \
    curl \
    bash \
    ca-certificates \
    unzip \
    fontconfig \
    -y && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/

# Development tools setup
RUN curl -fsSL https://starship.rs/install.sh -o /tmp/install_starship.sh && \
    chmod +x /tmp/install_starship.sh && \
    /tmp/install_starship.sh -y && \
    rm /tmp/install_starship.sh

RUN mkdir -p /etc/starship && \
    curl -fsSL https://starship.rs/presets/toml/gruvbox-rainbow.toml -o /etc/starship/starship.toml && \
    echo 'export STARSHIP_CONFIG=/etc/starship/starship.toml' >> /etc/bash.bashrc

RUN mkdir -p /usr/local/share/fonts && \
    curl -fsSL https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/FiraCode.zip -o /tmp/FiraCode-NerdFont.zip && \
    unzip /tmp/FiraCode-NerdFont.zip -d /usr/local/share/fonts && \
    rm /tmp/FiraCode-NerdFont.zip && \
    fc-cache -fv

RUN echo 'eval "$(starship init bash)"' >> /etc/bash.bashrc

# Node.js setup
# RUN mkdir -p dist node_modules && \
#     npm install -g npm@10.2.3 @nestjs/cli pnpm && \
#     chown -R node:node node_modules && \
#     npm cache clean --force

ARG GH_TOKEN
RUN npm install -g pnpm && \
    pnpm config set @Netlabs-Australia-Pty-Ltd:registry https://npm.pkg.github.com && \
    pnpm config set //npm.pkg.github.com/:_authToken "${GH_TOKEN}" && \
    pnpm config set always-auth true

USER node